"""Consent to reuse

Revision ID: 22cafefb37b9
Revises: 0490f73ca298
Create Date: 2026-02-06 11:11:39.816635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cafefb37b9'
down_revision: Union[str, None] = '0490f73ca298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('consent_to_reuse', sa.Boolean(), nullable=False))
    op.alter_column('images', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('images', 'consent_to_reuse')
    # ### end Alembic commands ###
